fix1

diff --git a/packages/lvm2/S06lvm2 b/packages/lvm2/S06lvm2
--- a/packages/lvm2/S06lvm2
+++ b/packages/lvm2/S06lvm2
@@ -1,17 +1,17 @@
 #!/bin/sh
 
-prefix="/opt"
+prefix="/Apps/opt"
 PATH=${prefix}/bin:${prefix}/sbin:/sbin:/bin:/usr/sbin:/usr/bin
 
 start() {
 	echo "starting lvm..."
-	/opt/sbin/lvm vgscan --ignorelockingfailure --mknodes || :
-	/opt/sbin/lvm vgchange -aly --ignorelockingfailure || echo "...failed"
+	/Apps/opt/sbin/lvm vgscan --ignorelockingfailure --mknodes || :
+	/Apps/opt/sbin/lvm vgchange -aly --ignorelockingfailure || echo "...failed"
 	}
 
 stop() {
 	echo "stopping lvm..."
-	/opt/sbin/lvm vgchange -aln --ignorelockingfailure || echo "...failed"
+	/Apps/opt/sbin/lvm vgchange -aln --ignorelockingfailure || echo "...failed"
 	}
 status() {
 	echo "PID of lvm is `pidof lvm`"
